# Install script for directory: /home/root/lib/apps

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/lib/libvoxl_io.so")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/lib" TYPE SHARED_LIBRARY FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/libvoxl_io.so")
  if(EXISTS "$ENV{DESTDIR}/usr/lib/libvoxl_io.so" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/lib/libvoxl_io.so")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/lib/libvoxl_io.so")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/include/voxl_io.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/include" TYPE FILE FILES "/home/root/lib/apps/../include/voxl_io.h")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-uart-loopback")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-uart-loopback")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-uart-loopback" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-uart-loopback")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-uart-loopback")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-test-time")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-test-time")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-test-time" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-test-time")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-test-time")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-gpio-loopback")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-gpio-loopback")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-gpio-loopback" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-gpio-loopback")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-gpio-loopback")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-gpio")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-gpio")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-gpio" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-gpio")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-gpio")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-i2c")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-i2c")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-i2c" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-i2c")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-i2c")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-spi")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-spi")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-spi" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-spi")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-spi")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-test-mavparser")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-test-mavparser")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-test-mavparser" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-test-mavparser")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-test-mavparser")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-open-uart")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-open-uart")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-open-uart" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-open-uart")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-open-uart")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-close-uart")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-close-uart")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-close-uart" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-close-uart")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-close-uart")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-read-uart")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-read-uart")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-read-uart" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-read-uart")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-read-uart")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-write-uart")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-write-uart")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-write-uart" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-write-uart")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-write-uart")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/voxl-parser")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE EXECUTABLE FILES "/home/root/build_apps/CMakeFiles/CMakeRelink.dir/voxl-parser")
  if(EXISTS "$ENV{DESTDIR}/usr/bin/voxl-parser" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}/usr/bin/voxl-parser")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/opt/Qualcomm/ARM_Tools/gcc-4.9-2014.11/bin/arm-linux-gnueabi-strip" "$ENV{DESTDIR}/usr/bin/voxl-parser")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/root/build_apps/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
